### ISSUE TITLE
wp_no_robots is deprecated

### ISSUE THREAD

**Issue by maciejmackowiak** [xwp/pwa-wp#529] opened 2021-06-02 10:30 UTC
Hi,
I've noticed several `wp_no_robots` is deprecated since version WP 5.7.0 messages in logs.
It is used here: https://github.com/GoogleChromeLabs/pwa-wp/blob/18c2932d41638c28e4816e7e28168c7ad135412b/wp-includes/general-template.php#L105
According to comments in WP core the `wp_robots_no_robots` should be used:
https://github.com/WordPress/WordPress/blob/524030edfa1f5f3a9ba18e4cb145a75c23e90c6e/wp-includes/deprecated.php#L4168

**Comment by westonruter** [comment] 2021-06-02 18:35
Yes, this is a duplicate of #414. It's fixed in `develop`, but just not yet released to WordPress.org.

**Closed as completed by westonruter** 2021-06-02 18:35 UTC
Labels: duplicate

**Comment by Gandhi11** [comment] 2021-06-02 18:48
@westonruter Do you have any idea of when it will be released to WordPress.org?

**Comment by westonruter** [comment] 2021-06-02 18:50
I don't, but a new release is overdue. Hopefully by end of the month.

**Comment by Gandhi11** [comment] 2021-06-02 18:52
Alright, thanks!
