### ISSUE TITLE
How do I get started with the plugin 

### ISSUE THREAD

**Issue by Benjazper** [xwp/pwa-wp#460] opened 2021-04-14 10:13 UTC
I've installed and activated. Do I need to do anything else? 

All I have to do is install and activated the plugin that is all. Right?

**Comment by Benjazper** [comment] 2021-04-14 13:08
@westonruter your reply will be very much appreciated 🙏🏾

**Comment by westonruter** [comment] 2021-04-14 14:43
Closing as duplicate of https://github.com/GoogleChromeLabs/pwa-wp/issues/459

**Closed as completed by westonruter** 2021-04-14 14:43 UTC
Labels: duplicate
